---
# Author
author:
  name: Мухина Ксения Николаевна
  email: 1032253531@pfur.ru
  affilation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 115419
      city: Москва
      address: ул. Орджоникидзе, д. 3

## Title
title: "Отчёт по лабораторной работе №2"
subtitle: "Дисциплина: Архитектура компьютеров"
licence: "CC BY-NC"
---

# Цель работы

Изучить применение средств контроля версий и приобрести практические навыки по работе с системой контроля версий Git.

# Выполнение лабораторной работы

Далее описываемая работа была выполнена на виртуальной машине Oracle VirtualBox с ОС Linux Ubuntu.

1. Настройка GitHub

...

2. Базовая настройка Git

...

3. Создание SSH-ключа

...

4. Создание рабочего пространства и репозитория курса на основе шаблона

...

5. Создание репозитория курса на основе шаблона

...

6. Настройка каталога курса

...

# Задания для самостоятельной работы

В соответствии с заданиями, указанными в лабораторной работе №3, данный отчёт будет создан в соответствующем каталоге рабочего пространства. Также отчёт будет скомпилирован в форматах .pdf и .docx. Данные файлы будут загружены на GitHub.

# Выводы

В ходе выполнения лабораторной работы мы изучили применение средств контроля версий и приобрели практические навыки по работе с системой контроля версий Git путём работы с репозиторием на сервере репозиториев GitHub.

# Список литературы{.unnumbered}

1. Файл ["Лабораторная работа №2. Система контроля версий Git.pdf"](https://esystem.rudn.ru/mod/resource/view.php?id=1297701)
